export const metadata = {
  title: "Verify Email | Auth Sandbox",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="grid grid-cols-3">
      <section className="col-start-2 flex min-h-screen items-center justify-center">
        {children}
      </section>
    </main>
  );
}
