import "~/styles/globals.css";

import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { AuthProvider } from "./_components/auth-provider";
import { Footer } from "./_components/footer";
import { Navbar } from "./_components/navbar";
import { ThemeProvider } from "./_components/ui/theme-provider";
import { Toaster } from "./_components/ui/toaster";

export const metadata = {
  title: {
    template: "%s | Auth Sandbox",
    default: "Auth Sandbox",
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

// This is the root layout. Everything except `children` is the same for all pages.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans flex min-h-screen flex-col">
        <TRPCReactProvider cookies={cookies().toString()}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <Navbar />

              {children}

              <Footer />

              <Toaster />
            </AuthProvider>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
