import "~/styles/globals.css";

import { cookies } from "next/headers";

import Link from "next/link";
import { TRPCReactProvider } from "~/trpc/react";
import { AuthProvider } from "./_components/auth-provider";
import { Navbar } from "./_components/navbar";
import { SessionTimer } from "./_components/session-timer";
import { ThemeProvider } from "./_components/ui/theme-provider";
import { Toaster } from "./_components/ui/toaster";

export const metadata = {
  title: {
    template: "%s | Auth Sandbox",
    default: "Auth Sandbox",
  },
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const footerLinks: { href: string; description: string }[] = [
  { href: "https://create.t3.gg/", description: "Create T3 App" },
  { href: "https://ui.shadcn.com", description: "shadcn/ui" },
  {
    href: "https://fonts.google.com/specimen/JetBrains+Mono",
    description: "JetBrains Mono",
  },
];

// This is the root layout. Everything except `children` is the same for all pages.
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans flex min-h-screen flex-col">
        <TRPCReactProvider cookies={cookies().toString()}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <AuthProvider>
              <Navbar />

              <SessionTimer className="text-center text-slate-400" />

              {children}

              <footer className="py-3">
                <ul className="flex justify-center divide-x divide-slate-500">
                  {footerLinks.map(({ href, description }) => (
                    <li key={href}>
                      <Link
                        href={href}
                        target="_blank"
                        className="px-5 text-slate-400 opacity-50 transition-opacity hover:opacity-100"
                      >
                        {description}
                      </Link>
                    </li>
                  ))}
                </ul>
              </footer>
              <Toaster />
            </AuthProvider>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
