import "~/styles/globals.css";

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Sign Up | Auth Sandbox",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main
      className={`font-sans ${inter.variable} grid min-h-screen grid-cols-3 max-lg:grid-cols-1`}
    >
      <section className="col-start-2 px-8 py-4 max-lg:col-start-1">
        {children}
      </section>
    </main>
  );
}
