export const metadata = {
  title: "Sign In | Auth Sandbox",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <main className="grid grow grid-cols-3 items-center max-lg:grid-cols-1">
      <section className="col-start-2 px-8 py-4 max-lg:col-start-1">
        {children}
      </section>
    </main>
  );
}
